"""build_taxonomy.py 생성물 — 직접 수정 금지.

data/장인몰_샘플_category.csv · 장인몰_샘플_product.csv 에서 자동으로 뽑았다.
실데이터가 바뀌면 재생성: python app/pipeline/build_taxonomy.py
"""

CATEGORY_LABELS: dict[str, str] = {
    'DYEING': '천연염색',
    'METAL': '금속공예',
    'NACRE': '나전칠기',
    'ONGGI': '옹기',
    'POTTERY': '도자기',
    'WOOD': '목공예',
}

# 소비자가 쓸 법한 단어(카테고리 한글명 + 카테고리를 유일하게 특정하는 재질·세부품목)
# → 카테고리 코드. generate.py의 카테고리 대조 방어가 이 사전으로 사용자 발화에서
# 카테고리를 뽑는다.
CATEGORY_SIGNALS: dict[str, str] = {
    '감물염': 'DYEING',
    '거울함': 'NACRE',
    '곡물독': 'ONGGI',
    '금속공예': 'METAL',
    '김치독': 'ONGGI',
    '나전': 'NACRE',
    '나전칠기': 'NACRE',
    '노리개': 'METAL',
    '놋쇠': 'METAL',
    '느티나무': 'WOOD',
    '다기받침': 'METAL',
    '다기세트': 'POTTERY',
    '다완': 'POTTERY',
    '대접': 'POTTERY',
    '도기토': 'POTTERY',
    '도마': 'WOOD',
    '도자기': 'POTTERY',
    '머그': 'POTTERY',
    '명주': 'DYEING',
    '모시': 'DYEING',
    '목공예': 'WOOD',
    '물항아리': 'ONGGI',
    '반닫이': 'WOOD',
    '방석': 'DYEING',
    '백동': 'METAL',
    '백자': 'POTTERY',
    '보석함': 'NACRE',
    '보자기': 'DYEING',
    '분청': 'POTTERY',
    '브로치': 'METAL',
    '삼베': 'DYEING',
    '서랍장': 'WOOD',
    '소나무': 'WOOD',
    '손수건': 'DYEING',
    '수반': 'POTTERY',
    '수저세트': 'METAL',
    '술독': 'ONGGI',
    '스카프': 'DYEING',
    '앞치마': 'DYEING',
    '오동나무': 'WOOD',
    '오배자염': 'DYEING',
    '옹기': 'ONGGI',
    '옻칠': 'NACRE',
    '유약토': 'ONGGI',
    '은행나무': 'WOOD',
    '의자': 'WOOD',
    '이불': 'DYEING',
    '자개': 'NACRE',
    '자개장식품': 'NACRE',
    '자작나무': 'WOOD',
    '잔받침': 'POTTERY',
    '장독': 'ONGGI',
    '장신구함': 'METAL',
    '전통옻칠': 'WOOD',
    '점토': 'ONGGI',
    '접시': 'POTTERY',
    '젓갈독': 'ONGGI',
    '주칠': 'NACRE',
    '쪽염': 'DYEING',
    '참나무': 'WOOD',
    '찻잔': 'POTTERY',
    '책상': 'WOOD',
    '천연염색': 'DYEING',
    '청동': 'METAL',
    '청자': 'POTTERY',
    '촛대': 'METAL',
    '치자염': 'DYEING',
    '테이블러너': 'DYEING',
    '파우치': 'DYEING',
    '한지': 'DYEING',
    '항아리': 'POTTERY',
    '향로': 'METAL',
    '홍화염': 'DYEING',
    '화병': 'POTTERY',
    '화분': 'ONGGI',
    '황토': 'ONGGI',
    '흑칠': 'NACRE',
}

# CATEGORY_SIGNALS에서 뺀 단어 — 값이 카테고리 코드 2개 이상이면 "여러 카테고리에 걸침"
# (예: "옹기토"는 POTTERY·ONGGI 양쪽 다 쓰인다), 안내문 하나뿐이면 "1글자라 오탐 위험"
# (예: "은"은 조사 "그릇은"과 구별 안 됨)이라는 뜻이다. 잘못 매칭돼 멀쩡한 후보를
# 지우는 게 매칭을 놓치는 것보다 위험해서 신호에서 제외했다.
AMBIGUOUS_TERMS: dict[str, list[str]] = {
    '면': ['(1글자 — 오탐 위험으로 제외)'],
    '문갑': ['NACRE', 'WOOD'],
    '소반': ['NACRE', 'WOOD'],
    '옹기토': ['ONGGI', 'POTTERY'],
    '은': ['(1글자 — 오탐 위험으로 제외)'],
    '트레이': ['NACRE', 'WOOD'],
    '함': ['(1글자 — 오탐 위험으로 제외)'],
}
